FROM quay.io/keycloak/keycloak:<%= image.version %> as builder

<% image.vars['keycloak_build_envvars'].each do |evar| -%>
ENV <%= evar %>
<% end -%>
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:<%= image.version %>

USER root
RUN microdnf update -y && microdnf install -y tar gzip wget && microdnf clean all

<%= snippet('labels', binding) -%>

# Add docker-entrypoint script base
RUN mkdir /docker-entrypoint.d/ \
 && wget -qO- https://github.com/itsbcit/docker-entrypoint/releases/download/v1.6/docker-entrypoint.tar.gz | tar xvz -C / \
 && chmod -R 555 /docker-entrypoint.* \
 && echo "UTC" > /etc/timezone \
 && chmod 664 /etc/passwd \
              /etc/group \
              /etc/shadow \
              /etc/timezone \
 && chown 0:0 /etc/shadow \
 && chmod 775 /etc

<%= snippet('tini', binding) -%>

USER keycloak 
COPY --from=builder /opt/keycloak/ /opt/keycloak/
COPY ../bcit-keycloak-theme.jar /opt/keycloak/providers/bcit-keycloak-theme.jar
WORKDIR /opt/keycloak

ENTRYPOINT ["/tini", "--", "/docker-entrypoint.sh"]
CMD ["/opt/keycloak/bin/kc.sh", "start"]

